#! /bin/bash
#
# Build frontend files for nodebug environment.
#
# When CORE_DEBUG is false in the web/index_* controller, the web response
# class will generate urls for ".min.js" instead of ".juicy.js", and similarly
# for css files. So in production and staging Juicer runtime is bypassed,
# the minified files are used directly.
#
# Usage:
#   Run from the root folder!
#   $ batch/build
#
# @see /apps/revtk/lib/rtkWebResponse.php
#
# @author:  Fabrice Denis
#


# OBSOLETE - WILL BE REMOVED WHEN JUICER ENABLED EVERYWHERE
java -jar batch/tools/yuicompressor/yuicompressor-2.4.2.jar web/js/ui/uibase.js -o web/js/ui/uibase.min.js


# labs-alpha-flashcardreview.js
php lib/juicer/JuicerCLI.php -v --webroot web --config apps/revtk/config/juicer.config.php --infile web/revtk/labs-alpha-flashcardreview.juicy.js
java -jar batch/tools/yuicompressor/yuicompressor-2.4.2.jar web/revtk/labs-alpha-flashcardreview.juiced.js -o web/revtk/labs-alpha-flashcardreview.min.js
# labs-alpha-flashcardreview.css
php lib/juicer/JuicerCLI.php -v --webroot web --config apps/revtk/config/juicer.config.php --infile web/revtk/labs-alpha-flashcardreview.juicy.css
java -jar batch/tools/yuicompressor/yuicompressor-2.4.2.jar web/revtk/labs-alpha-flashcardreview.juiced.css -o web/revtk/labs-alpha-flashcardreview.min.css

# bundles/flashcardreview-1.0.js
php lib/juicer/JuicerCLI.php -v --webroot web --config apps/revtk/config/juicer.config.php --infile web/revtk/bundles/flashcardreview-1.0.juicy.js
java -jar batch/tools/yuicompressor/yuicompressor-2.4.2.jar web/revtk/bundles/flashcardreview-1.0.juiced.js -o web/revtk/bundles/flashcardreview-1.0.min.js
# bundles/flashcardreview-1.0.css
php lib/juicer/JuicerCLI.php -v --webroot web --config apps/revtk/config/juicer.config.php --infile web/revtk/bundles/flashcardreview-1.0.juicy.css
java -jar batch/tools/yuicompressor/yuicompressor-2.4.2.jar web/revtk/bundles/flashcardreview-1.0.juiced.css -o web/revtk/bundles/flashcardreview-1.0.min.css

# study-base.js
php lib/juicer/JuicerCLI.php -v --webroot web --config apps/revtk/config/juicer.config.php --infile web/revtk/study-base.juicy.js
java -jar batch/tools/yuicompressor/yuicompressor-2.4.2.jar web/revtk/study-base.juiced.js -o web/revtk/study-base.min.js


# kanji-flashcardreview.js
php lib/juicer/JuicerCLI.php -v --webroot web --config apps/revtk/config/juicer.config.php --infile web/revtk/kanji-flashcardreview.juicy.js
java -jar batch/tools/yuicompressor/yuicompressor-2.4.2.jar web/revtk/kanji-flashcardreview.juiced.js -o web/revtk/kanji-flashcardreview.min.js
# kanji-flashcardreview.css
php lib/juicer/JuicerCLI.php -v --webroot web --config apps/revtk/config/juicer.config.php --infile web/revtk/kanji-flashcardreview.juicy.css
java -jar batch/tools/yuicompressor/yuicompressor-2.4.2.jar web/revtk/kanji-flashcardreview.juiced.css -o web/revtk/kanji-flashcardreview.min.css

# review-home.js
php lib/juicer/JuicerCLI.php -v --webroot web --config apps/revtk/config/juicer.config.php --infile web/revtk/review-home.juicy.js
java -jar batch/tools/yuicompressor/yuicompressor-2.4.2.jar web/revtk/review-home.juiced.js -o web/revtk/review-home.min.js
# review-home.css
php lib/juicer/JuicerCLI.php -v --webroot web --config apps/revtk/config/juicer.config.php --infile web/revtk/review-home.juicy.css
java -jar batch/tools/yuicompressor/yuicompressor-2.4.2.jar web/revtk/review-home.juiced.css -o web/revtk/review-home.min.css

# build version file for revisioning css & js assets
mv config/versioning.inc.php config/.versioning.inc.php
php batch/build_app.php --webroot web --out config/versioning.inc.php

